name: Deploy React App
on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: divulgaif-vps

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          rm -rf node_modules
          npm install

      - name: Build React app
        env:
          REACT_APP_SUAP_CLIENT_ID: 1aJjdqqzsur8URjIDDnRyz5TMoVrOfA0MQQhYdCu
          REACT_APP_SUAP_SCOPE: "identificacao email"
          REACT_APP_SUAP_PROVIDER: cHJvdmVkb3IgZGEgYXBpIGRvIHN1YXAgZG8gZGl2dWxnYWlmLmNvbS5iciBtdWl0byB0b3AgZGVtYWlzIGVtIHNlIHRhIGRvaWRv
        run: |
          if [[ $GITHUB_REF == refs/heads/main ]]; then
            npm run build
          else
            npm run build:dev
          fi

      - name: Determine deployment directory
        id: deployment
        run: |
          if [[ $GITHUB_REF == refs/heads/main ]]; then
            echo "target_dir=/var/www/divulgaif" >> $GITHUB_OUTPUT
          else
            echo "target_dir=/var/www/dev-divulgaif" >> $GITHUB_OUTPUT
          fi

      - name: Clean deployment directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            rm -rf ${{ steps.deployment.outputs.target_dir }}/*
            mkdir -p ${{ steps.deployment.outputs.target_dir }}
            echo "Preparing to copy files..."

      - name: Copy build files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          source: "build/*"
          target: "${{ steps.deployment.outputs.target_dir }}"
          strip_components: 1

      - name: Set permissions and reload Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            chmod -R 755 ${{ steps.deployment.outputs.target_dir }}
            chown -R www-data:www-data ${{ steps.deployment.outputs.target_dir }}
            sudo systemctl reload nginx
